server:
  port: 8081


spring:
  jwt:
    secret=jwtsecretkey:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:oracle:thin:@localhost:1521:xe

#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: sys as sysdba
    password: 1234
  thymeleaf:
    cache: false

jpa:
  properties:
    hibernate:
      format_sql: true
      user_sql_cooments: true

  hibernate:
    ddl-auto: create
