encoding: UTF-8
server:
  port: 8081


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: sys as sysdba
    password: 1234
  thymeleaf:
    cache: false

jpa:
  database-platform: org.hibernate.dialect.OracleDialect
  hibernate:
    ddl-auto: update
  show-sql: true


jwt:
  secret:
    key: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff